Blocked access to external URL http://www.localhost:8800/fetch/metadata/resources/record-headers.py?key=GENERATED_KEY

Harness Error (TIMEOUT), message = null

FAIL sec-fetch-site - Not sent to non-trustworthy same-origin destination no attributes assert_not_own_property: unexpected property "sec-fetch-site" is found on object
TIMEOUT sec-fetch-site - Not sent to non-trustworthy same-site destination no attributes Test timed out
NOTRUN sec-fetch-site - Not sent to non-trustworthy cross-site destination no attributes
NOTRUN sec-fetch-mode - Not sent to non-trustworthy same-origin destination no attributes
NOTRUN sec-fetch-mode - Not sent to non-trustworthy same-site destination no attributes
NOTRUN sec-fetch-mode - Not sent to non-trustworthy cross-site destination no attributes
NOTRUN sec-fetch-dest - Not sent to non-trustworthy same-origin destination no attributes
NOTRUN sec-fetch-dest - Not sent to non-trustworthy same-site destination no attributes
NOTRUN sec-fetch-dest - Not sent to non-trustworthy cross-site destination no attributes
NOTRUN sec-fetch-user - Not sent to non-trustworthy same-origin destination no attributes
NOTRUN sec-fetch-user - Not sent to non-trustworthy same-site destination no attributes
NOTRUN sec-fetch-user - Not sent to non-trustworthy cross-site destination no attributes
NOTRUN sec-fetch-site - HTTPS downgrade (header not sent) no attributes
NOTRUN sec-fetch-site - HTTPS upgrade no attributes
NOTRUN sec-fetch-site - HTTPS downgrade-upgrade no attributes

